name: "ir_decoder: Build and lint"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'ufbt: Build for Dev Branch'
    steps:
      - uses: actions/checkout@v4
      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build-app
        with:
          sdk-channel: dev
          app-dir: infrared/apps/ir_decoder
      - name: Upload app artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "ir_decoder-${{ steps.build-app.outputs.suffix }}"
          path: ${{ steps.build-app.outputs.fap-artifacts }}
      - name: Lint sources
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        with:
          skip-setup: true
          task: lint
          app-dir: infrared/apps/ir_decoder
