name: "hex_viewer: Build and lint"

on:
  push:
    branches: [ master ]
    paths:
      - ".github/workflows/build_hex_viewer.yaml"
      - "tools/apps/hex_viewer/**"
  pull_request:
    branches: [ master ]
    paths:
      - ".github/workflows/build_hex_viewer.yaml"
      - "tools/apps/hex_viewer/**"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        sdk-version: ["release", "dev", "rc"]
    runs-on: ubuntu-latest
    name: 'ufbt: Build for ${{ matrix.sdk-version }} Branch'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build-app
        with:
          sdk-channel: ${{ matrix.sdk-version }}
          app-dir: tools/apps/hex_viewer
      - name: Upload app artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "flipperzero-hex_viewer-${{ matrix.sdk-version }}-${{ steps.build-app.outputs.suffix }}"
          path: ${{ steps.build-app.outputs.fap-artifacts }}
      - name: Lint sources
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        continue-on-error: true
        with:
          skip-setup: true
          task: lint
          app-dir: tools/apps/hex_viewer
